version: '2'
services:
    datapoolgenerator-app:
        image: datapoolgenerator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://datapoolgenerator-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=DataPoolGenerator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    datapoolgenerator-mongodb:
        extends:
            file: mongodb.yml
            service: datapoolgenerator-mongodb
